# frozen_string_literal: true

require_relative 'common_style'
require_relative 'default_palette'
require_relative 'diagram'
require_relative 'node'
require_relative 'node_list'
require_relative 'page'

require_relative 'layouts/layout'
require_relative 'layouts/flex_layout'
require_relative 'layouts/grid_layout'

require_relative 'shapes/shape'
require_relative 'shapes/h1'
require_relative 'shapes/h2'
require_relative 'shapes/h3'
require_relative 'shapes/h4'
require_relative 'shapes/h5'
require_relative 'shapes/h6'
require_relative 'shapes/p'
require_relative 'shapes/actor'
require_relative 'shapes/actor2'
require_relative 'shapes/callout'
require_relative 'shapes/callout2'
require_relative 'shapes/callout3'
require_relative 'shapes/callout4'
require_relative 'shapes/circle'
require_relative 'shapes/cloud'
require_relative 'shapes/container'
require_relative 'shapes/container2'
require_relative 'shapes/container3'
require_relative 'shapes/container4'
require_relative 'shapes/cross'
require_relative 'shapes/envelop'
require_relative 'shapes/diamond'
require_relative 'shapes/document'
require_relative 'shapes/ellipse'
require_relative 'shapes/hexagon'
require_relative 'shapes/interface'
require_relative 'shapes/klass'
require_relative 'shapes/note'
require_relative 'shapes/process'
require_relative 'shapes/rectangle'
require_relative 'shapes/rectangle2'
require_relative 'shapes/square'
require_relative 'shapes/step'
require_relative 'shapes/tick'
require_relative 'shapes/face'
require_relative 'shapes/triangle'
require_relative 'shapes/embed_row'
require_relative 'shapes/embed_col50'
require_relative 'shapes/embed_col200'

require_relative 'virtual/anchor'
